Resources:
  MyIAMUser:
    Type: AWS::IAM::User
    Properties:
      Groups: 
      - teja 
      UserName: 'tejal'
      LoginProfile: 
        Password: "teja*1234"
        PasswordResetRequired: "false"
      Path: /
      Policies: 
      - PolicyName: "Devaccess"
        PolicyDocument:
          statement:
          - Effect: "Allow"
            Action: "ec2:*" 
            Resource: '*'
      Tags:      
      - Key: 'name'
        Value: 'teja-p'
